name: Appwrite Keep Alive
on:
  schedule:
    - cron: '0 0 */4 * *' # Runs at midnight every 4 days
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Appwrite Database
        run: |
          curl -X GET "${{ secrets.VITE_APPWRITE_URL }}/databases/${{ secrets.VITE_APPWRITE_DATABASE_ID }}/collections/${{ secrets.VITE_APPWRITE_COLLECTION_PRODUCTS }}/documents" \
          -H "X-Appwrite-Project: ${{ secrets.VITE_APPWRITE_PROJECT_ID }}"